<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ToleranceConverter</RootNamespace>
    <Nullable>enable</Nullable>
    
    <!-- ?????? - ?????? -->
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="tolerance_table.json" />
  </ItemGroup>

</Project>
